#!/usr/bin/env python

from waflib.TaskGen import before_method, after_method, feature

def build(bld):
	bld(
		source="monome.pyx",
		features="c cshlib pyext",

		target="monome",
		name="monome_pyext",
		use="monome")
