#!/usr/bin/env python

from waflib.TaskGen import before_method, after_method, feature

top = ".."

@feature("proto_module")
@before_method('propagate_uselib_vars', 'apply_link')
@after_method('apply_bundle')
def proto_module(self):
	"""
	removes 'lib' from cshlib_PATTERN if it's there.
	"""

	pat = self.env["cshlib_PATTERN"]
	if pat[:3] == "lib":
		pat = pat[3:]
		self.env['cshlib_PATTERN'] = self.env['cxxshlib_PATTERN'] = pat

@feature("force_lib_prefix")
@before_method('propagate_uselib_vars', 'apply_link')
@after_method('apply_bundle')
def force_lib_prefix(self):
	"""
	adds 'lib' to cshlib_PATTERN if it's not there.
	"""

	pat = self.env["cshlib_PATTERN"]
	if pat[:3] != "lib":
		pat = "lib{0}".format(pat)
		self.env['cshlib_PATTERN'] = self.env['cxxshlib_PATTERN'] = pat

def build(bld):
	# ".." includes the build directory (for config.h)
	bld(export_includes=".. ../public private", name="lm_inc")

	objs = []
	obj = lambda src: objs.append(src)

	#
	# platform
	#

	if bld.env.DEST_OS == "linux":
		if bld.env.LIB_UDEV:
			obj("platform/linux_libudev.c")
		else:
			obj("platform/linux_sysfs.c")

		obj("platform/linux.c")
		obj("platform/posix.c")

	elif bld.env.DEST_OS == "darwin":
		obj("platform/darwin.c")
		obj("platform/posix.c")

	elif bld.env.DEST_OS == "win32":
		obj("platform/windows.c")

	print(bld.env)

	#
	# protocols
	#

	for p in bld.env.PROTOCOLS:
		bld.shlib(
			source="proto/{0}.c".format(p),
			features="proto_module",
			use="lm_inc monome",

			target="protocol_{0}".format(p),
			install_path="${LIBDIR}/monome")

	if bld.env.LIB_LO:
		bld.shlib(
			source="proto/osc.c",
			features="proto_module",
			use="lm_inc LO",

			target="protocol_osc",
			install_path="${LIBDIR}/monome")

	#
	# common
	#

	obj("rotation.c")
	obj("libmonome.c")

	if bld.env.DEST_OS == "win32":
		bld.shlib(
			source=objs,
			features="force_lib_prefix",
			use="lm_inc",

			target="monome")
	else:
		# the UDEV use is ignored if it is not defined
		bld.shlib(
			source=objs,
			use="lm_inc UDEV",

			target="monome",
			vnum=bld.env.VERSION)

	if bld.env.LIB_LO:
		bld.program(
			source="monomeserial.c",
			use="lm_inc monome LO",

			target="monomeserial")
